import { User } from '../types/auth';
import { StudentRecord, LeaderboardEntry } from '../types/student';
import { 
  ClassAnalyticsData, 
  TestPaper, 
  MockAssignment, 
  WeakTopicItem, 
  TestDiagnosticResult 
} from '../types/test';

export const DEMO_TEACHER_USER: User = {
  id: 't-01',
  role: 'teacher',
  name: 'Dr. Vikram Malhotra',
  email: 'vikram.malhotra@brothersacademy.edu',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
  subjectSpecialization: 'Senior Faculty & Physics Head',
  xp: 0,
  streak: 0,
};

export const DEMO_STUDENT_USER: User = {
  id: 's-01',
  role: 'student',
  name: 'Rohan Sharma',
  email: 'rohan.sharma@brothersacademy.edu',
  avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=200&auto=format&fit=crop',
  batch: 'Batch A1 (JEE Advanced 2026)',
  grade: 'Grade 12',
  xp: 1240,
  streak: 15,
};

export const BATCH_LIST = [
  'Batch A1 (JEE Advanced 2026)',
  'Batch B1 (NEET Elite Target)',
  'Batch C1 (JEE Main & Foundation)',
];

export const MOCK_STUDENTS: StudentRecord[] = [
  {
    id: 's-01',
    name: 'Rohan Sharma',
    email: 'rohan.sharma@brothersacademy.edu',
    rollNumber: 'BA-2026-101',
    batch: 'Batch A1 (JEE Advanced 2026)',
    grade: 'Grade 12',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=200&auto=format&fit=crop',
    overallRank: 4,
    totalTests: 7,
    averageScore: 74.2,
    averageAccuracy: 82.5,
    xp: 1240,
    streak: 15,
    scoreHistory: [
      { testId: 't-01', testNumber: 'Test 1', testTitle: 'Kinematics & Basic Calculus', date: '2026-06-15', score: 45, totalMarks: 100, percentage: 45, rank: 14, physicsScore: 22, chemistryScore: 12, mathsScore: 11, accuracy: 58 },
      { testId: 't-02', testNumber: 'Test 2', testTitle: 'Thermodynamics & Mole Concept', date: '2026-06-28', score: 52, totalMarks: 100, percentage: 52, rank: 12, physicsScore: 24, chemistryScore: 18, mathsScore: 10, accuracy: 64 },
      { testId: 't-03', testNumber: 'Test 3', testTitle: 'Organic Mechanisms & Trigonometry', date: '2026-07-10', score: 48, totalMarks: 100, percentage: 48, rank: 13, physicsScore: 18, chemistryScore: 15, mathsScore: 15, accuracy: 61 },
      { testId: 't-04', testNumber: 'Test 4', testTitle: 'Calculus & Coordinate Geometry', date: '2026-07-22', score: 61, totalMarks: 100, percentage: 61, rank: 8, physicsScore: 26, chemistryScore: 20, mathsScore: 15, accuracy: 72 },
      { testId: 't-05', testNumber: 'Test 5', testTitle: 'Electrostatics & Hydrodynamics', date: '2026-08-01', score: 59, totalMarks: 100, percentage: 59, rank: 9, physicsScore: 25, chemistryScore: 19, mathsScore: 15, accuracy: 70 },
      { testId: 't-06', testNumber: 'Test 6', testTitle: 'Weekly Physics - Rotational Mechanics', date: '2026-08-08', score: 68, totalMarks: 100, percentage: 68, rank: 6, physicsScore: 32, chemistryScore: 21, mathsScore: 15, accuracy: 78 },
      { testId: 't-07', testNumber: 'Test 7', testTitle: 'Full Syllabus Mock Test #7', date: '2026-08-14', score: 120, totalMarks: 160, percentage: 75, rank: 4, physicsScore: 42, chemistryScore: 46, mathsScore: 32, accuracy: 82 },
    ],
    subjectMastery: [
      { subject: 'Physics', masteryPercentage: 78, color: 'bg-indigo-600', bgLight: 'bg-indigo-100', weakTopicsCount: 2, totalQuestionsAttempted: 140 },
      { subject: 'Chemistry', masteryPercentage: 92, color: 'bg-emerald-600', bgLight: 'bg-emerald-100', weakTopicsCount: 1, totalQuestionsAttempted: 135 },
      { subject: 'Mathematics', masteryPercentage: 65, color: 'bg-amber-600', bgLight: 'bg-amber-100', weakTopicsCount: 3, totalQuestionsAttempted: 125 },
    ],
    mistakes: [
      {
        id: 'm-01',
        testId: 't-07',
        testTitle: 'Full Syllabus Mock Test #7',
        questionNumber: 4,
        subject: 'Physics',
        topic: 'Rotational Kinematics',
        subtopic: 'Angular Acceleration & Torque',
        questionText: 'A solid cylinder of mass M and radius R is pulled by a horizontal force F at its highest point on a rough horizontal surface. Find the acceleration of center of mass.',
        studentOption: 'B',
        correctOption: 'D',
        errorType: 'Conceptual',
        aiExplanation: 'You calculated linear translation without accounting for the friction couple opposing rolling slipping.',
        remediationAction: 'Review pure rolling dynamics on rough planes.',
      },
      {
        id: 'm-02',
        testId: 't-07',
        testTitle: 'Full Syllabus Mock Test #7',
        questionNumber: 11,
        subject: 'Chemistry',
        topic: 'Stoichiometry Limiting Reagents',
        subtopic: 'Combustion Analysis',
        questionText: 'When 4.4g of propane is combusted with 16g of O2, what is the maximum mass of CO2 formed?',
        studentOption: 'A',
        correctOption: 'C',
        errorType: 'Calculation',
        aiExplanation: 'You did not normalize by molecular weights (propane = 44 g/mol) before finding the limiting reagent.',
        remediationAction: 'Check molar ratios before computing product masses.',
      },
      {
        id: 'm-03',
        testId: 't-07',
        testTitle: 'Full Syllabus Mock Test #7',
        questionNumber: 19,
        subject: 'Mathematics',
        topic: 'Definite Integrals',
        subtopic: 'Leibniz Integral Rule',
        questionText: 'Evaluate the derivative of the integral from 0 to x^2 of sin(t^2) dt with respect to x.',
        studentOption: 'B',
        correctOption: 'C',
        errorType: 'Sign Error',
        aiExplanation: 'Forgot chain rule factor (2x) when differentiating the upper limit x^2.',
        remediationAction: 'Practice Leibniz Rule on composite boundary functions.',
      },
      {
        id: 'm-04',
        testId: 't-06',
        testTitle: 'Weekly Physics - Rotational Mechanics',
        questionNumber: 8,
        subject: 'Physics',
        topic: 'Moment of Inertia',
        subtopic: 'Parallel Axis Theorem',
        questionText: 'Find moment of inertia of a uniform semicircular wire of mass M and radius R about an axis perpendicular to its plane through center of mass.',
        studentOption: 'C',
        correctOption: 'A',
        errorType: 'Conceptual',
        aiExplanation: 'Center of mass of semicircular wire is at 2R/pi from diameter, not 4R/3pi.',
        remediationAction: 'Memorize centroid coordinates of standard arc shapes.',
      },
    ],
    badges: [
      { id: 'b-01', title: '15-Day Streak Master', description: 'Maintained active problem solving for 15 straight days', icon: 'Flame', isUnlocked: true, unlockedAt: '2026-08-14', tier: 'gold' },
      { id: 'b-02', title: 'Chemistry Maestro', description: 'Scored >90% in 3 consecutive chemistry tests', icon: 'FlaskConical', isUnlocked: true, unlockedAt: '2026-08-10', tier: 'gold' },
      { id: 'b-03', title: 'Rapid OMR Submitter', description: 'Uploaded test within 30 minutes of test conclusion', icon: 'Zap', isUnlocked: true, unlockedAt: '2026-08-08', tier: 'silver' },
      { id: 'b-04', title: 'Math Marathoner', description: 'Complete 100 calculus verification MCQs', icon: 'Calculator', isUnlocked: false, tier: 'diamond' },
    ],
  },
  {
    id: 's-02',
    name: 'Aarav Mehta',
    email: 'aarav.mehta@brothersacademy.edu',
    rollNumber: 'BA-2026-102',
    batch: 'Batch A1 (JEE Advanced 2026)',
    grade: 'Grade 12',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop',
    overallRank: 1,
    totalTests: 7,
    averageScore: 91.5,
    averageAccuracy: 94.0,
    xp: 2450,
    streak: 28,
    scoreHistory: [
      { testId: 't-07', testNumber: 'Test 7', testTitle: 'Full Syllabus Mock Test #7', date: '2026-08-14', score: 152, totalMarks: 160, percentage: 95.0, rank: 1, physicsScore: 52, chemistryScore: 50, mathsScore: 50, accuracy: 96 },
    ],
    subjectMastery: [
      { subject: 'Physics', masteryPercentage: 94, color: 'bg-indigo-600', bgLight: 'bg-indigo-100', weakTopicsCount: 0, totalQuestionsAttempted: 160 },
      { subject: 'Chemistry', masteryPercentage: 96, color: 'bg-emerald-600', bgLight: 'bg-emerald-100', weakTopicsCount: 0, totalQuestionsAttempted: 160 },
      { subject: 'Mathematics', masteryPercentage: 90, color: 'bg-amber-600', bgLight: 'bg-amber-100', weakTopicsCount: 1, totalQuestionsAttempted: 160 },
    ],
    mistakes: [],
    badges: [
      { id: 'b-01', title: 'Top of the Podium', description: 'Rank #1 in Batch A1', icon: 'Crown', isUnlocked: true, unlockedAt: '2026-08-14', tier: 'diamond' },
    ],
  },
  {
    id: 's-03',
    name: 'Ananya Iyer',
    email: 'ananya.iyer@brothersacademy.edu',
    rollNumber: 'BA-2026-103',
    batch: 'Batch A1 (JEE Advanced 2026)',
    grade: 'Grade 12',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
    overallRank: 2,
    totalTests: 7,
    averageScore: 88.0,
    averageAccuracy: 91.2,
    xp: 2120,
    streak: 21,
    scoreHistory: [
      { testId: 't-07', testNumber: 'Test 7', testTitle: 'Full Syllabus Mock Test #7', date: '2026-08-14', score: 144, totalMarks: 160, percentage: 90.0, rank: 2, physicsScore: 48, chemistryScore: 48, mathsScore: 48, accuracy: 92 },
    ],
    subjectMastery: [
      { subject: 'Physics', masteryPercentage: 91, color: 'bg-indigo-600', bgLight: 'bg-indigo-100', weakTopicsCount: 1, totalQuestionsAttempted: 155 },
      { subject: 'Chemistry', masteryPercentage: 92, color: 'bg-emerald-600', bgLight: 'bg-emerald-100', weakTopicsCount: 0, totalQuestionsAttempted: 150 },
      { subject: 'Mathematics', masteryPercentage: 88, color: 'bg-amber-600', bgLight: 'bg-amber-100', weakTopicsCount: 1, totalQuestionsAttempted: 150 },
    ],
    mistakes: [],
    badges: [],
  },
  {
    id: 's-04',
    name: 'Devansh Patel',
    email: 'devansh.patel@brothersacademy.edu',
    rollNumber: 'BA-2026-104',
    batch: 'Batch A1 (JEE Advanced 2026)',
    grade: 'Grade 12',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
    overallRank: 3,
    totalTests: 7,
    averageScore: 82.4,
    averageAccuracy: 86.0,
    xp: 1890,
    streak: 18,
    scoreHistory: [
      { testId: 't-07', testNumber: 'Test 7', testTitle: 'Full Syllabus Mock Test #7', date: '2026-08-14', score: 132, totalMarks: 160, percentage: 82.5, rank: 3, physicsScore: 46, chemistryScore: 44, mathsScore: 42, accuracy: 88 },
    ],
    subjectMastery: [
      { subject: 'Physics', masteryPercentage: 85, color: 'bg-indigo-600', bgLight: 'bg-indigo-100', weakTopicsCount: 1, totalQuestionsAttempted: 145 },
      { subject: 'Chemistry', masteryPercentage: 84, color: 'bg-emerald-600', bgLight: 'bg-emerald-100', weakTopicsCount: 1, totalQuestionsAttempted: 140 },
      { subject: 'Mathematics', masteryPercentage: 82, color: 'bg-amber-600', bgLight: 'bg-amber-100', weakTopicsCount: 1, totalQuestionsAttempted: 140 },
    ],
    mistakes: [],
    badges: [],
  },
  {
    id: 's-05',
    name: 'Ishita Gupta',
    email: 'ishita.gupta@brothersacademy.edu',
    rollNumber: 'BA-2026-105',
    batch: 'Batch A1 (JEE Advanced 2026)',
    grade: 'Grade 12',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop',
    overallRank: 5,
    totalTests: 7,
    averageScore: 71.0,
    averageAccuracy: 77.5,
    xp: 1100,
    streak: 11,
    scoreHistory: [
      { testId: 't-07', testNumber: 'Test 7', testTitle: 'Full Syllabus Mock Test #7', date: '2026-08-14', score: 114, totalMarks: 160, percentage: 71.25, rank: 5, physicsScore: 38, chemistryScore: 42, mathsScore: 34, accuracy: 79 },
    ],
    subjectMastery: [
      { subject: 'Physics', masteryPercentage: 72, color: 'bg-indigo-600', bgLight: 'bg-indigo-100', weakTopicsCount: 2, totalQuestionsAttempted: 130 },
      { subject: 'Chemistry', masteryPercentage: 78, color: 'bg-emerald-600', bgLight: 'bg-emerald-100', weakTopicsCount: 1, totalQuestionsAttempted: 135 },
      { subject: 'Mathematics', masteryPercentage: 68, color: 'bg-amber-600', bgLight: 'bg-amber-100', weakTopicsCount: 2, totalQuestionsAttempted: 120 },
    ],
    mistakes: [],
    badges: [],
  },
  {
    id: 's-06',
    name: 'Kabir Verma',
    email: 'kabir.verma@brothersacademy.edu',
    rollNumber: 'BA-2026-106',
    batch: 'Batch A1 (JEE Advanced 2026)',
    grade: 'Grade 12',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
    overallRank: 6,
    totalTests: 7,
    averageScore: 66.5,
    averageAccuracy: 73.0,
    xp: 950,
    streak: 9,
    scoreHistory: [
      { testId: 't-07', testNumber: 'Test 7', testTitle: 'Full Syllabus Mock Test #7', date: '2026-08-14', score: 104, totalMarks: 160, percentage: 65.0, rank: 6, physicsScore: 34, chemistryScore: 38, mathsScore: 32, accuracy: 74 },
    ],
    subjectMastery: [
      { subject: 'Physics', masteryPercentage: 66, color: 'bg-indigo-600', bgLight: 'bg-indigo-100', weakTopicsCount: 3, totalQuestionsAttempted: 120 },
      { subject: 'Chemistry', masteryPercentage: 70, color: 'bg-emerald-600', bgLight: 'bg-emerald-100', weakTopicsCount: 2, totalQuestionsAttempted: 125 },
      { subject: 'Mathematics', masteryPercentage: 62, color: 'bg-amber-600', bgLight: 'bg-amber-100', weakTopicsCount: 3, totalQuestionsAttempted: 115 },
    ],
    mistakes: [],
    badges: [],
  },
  {
    id: 's-07',
    name: 'Priya Nair',
    email: 'priya.nair@brothersacademy.edu',
    rollNumber: 'BA-2026-107',
    batch: 'Batch A1 (JEE Advanced 2026)',
    grade: 'Grade 12',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop',
    overallRank: 7,
    totalTests: 7,
    averageScore: 61.2,
    averageAccuracy: 69.4,
    xp: 820,
    streak: 6,
    scoreHistory: [
      { testId: 't-07', testNumber: 'Test 7', testTitle: 'Full Syllabus Mock Test #7', date: '2026-08-14', score: 96, totalMarks: 160, percentage: 60.0, rank: 7, physicsScore: 30, chemistryScore: 36, mathsScore: 30, accuracy: 70 },
    ],
    subjectMastery: [
      { subject: 'Physics', masteryPercentage: 60, color: 'bg-indigo-600', bgLight: 'bg-indigo-100', weakTopicsCount: 3, totalQuestionsAttempted: 110 },
      { subject: 'Chemistry', masteryPercentage: 65, color: 'bg-emerald-600', bgLight: 'bg-emerald-100', weakTopicsCount: 2, totalQuestionsAttempted: 115 },
      { subject: 'Mathematics', masteryPercentage: 58, color: 'bg-amber-600', bgLight: 'bg-amber-100', weakTopicsCount: 4, totalQuestionsAttempted: 105 },
    ],
    mistakes: [],
    badges: [],
  },
  {
    id: 's-08',
    name: 'Siddharth Joshi',
    email: 'siddharth.joshi@brothersacademy.edu',
    rollNumber: 'BA-2026-108',
    batch: 'Batch A1 (JEE Advanced 2026)',
    grade: 'Grade 12',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=200&auto=format&fit=crop',
    overallRank: 8,
    totalTests: 7,
    averageScore: 54.0,
    averageAccuracy: 62.0,
    xp: 680,
    streak: 4,
    scoreHistory: [
      { testId: 't-07', testNumber: 'Test 7', testTitle: 'Full Syllabus Mock Test #7', date: '2026-08-14', score: 84, totalMarks: 160, percentage: 52.5, rank: 8, physicsScore: 26, chemistryScore: 32, mathsScore: 26, accuracy: 63 },
    ],
    subjectMastery: [
      { subject: 'Physics', masteryPercentage: 52, color: 'bg-indigo-600', bgLight: 'bg-indigo-100', weakTopicsCount: 4, totalQuestionsAttempted: 100 },
      { subject: 'Chemistry', masteryPercentage: 58, color: 'bg-emerald-600', bgLight: 'bg-emerald-100', weakTopicsCount: 3, totalQuestionsAttempted: 105 },
      { subject: 'Mathematics', masteryPercentage: 50, color: 'bg-amber-600', bgLight: 'bg-amber-100', weakTopicsCount: 4, totalQuestionsAttempted: 95 },
    ],
    mistakes: [],
    badges: [],
  },
];

export const MOCK_CLASS_ANALYTICS: ClassAnalyticsData = {
  batch: 'Batch A1 (JEE Advanced 2026)',
  totalTestsConducted: 7,
  classAverageScore: 68.4,
  averageAccuracy: 76.2,
  activeStudentCount: 48,
  subjectAverages: {
    physics: 66.2,
    chemistry: 74.5,
    maths: 64.8,
  },
  performanceTrends: [
    { testNumber: 'Test 1', testTitle: 'Kinematics & Mole Concept', classAverage: 54.2, highestScore: 88, lowestScore: 32, targetBenchmark: 65 },
    { testNumber: 'Test 2', testTitle: 'Thermodynamics & Calculus', classAverage: 58.6, highestScore: 92, lowestScore: 36, targetBenchmark: 65 },
    { testNumber: 'Test 3', testTitle: 'Organic Chemistry & Vectors', classAverage: 62.1, highestScore: 90, lowestScore: 38, targetBenchmark: 70 },
    { testNumber: 'Test 4', testTitle: 'Electrostatics & Coordinate Geo', classAverage: 60.5, highestScore: 94, lowestScore: 40, targetBenchmark: 70 },
    { testNumber: 'Test 5', testTitle: 'Magnetism & Chemical Bonding', classAverage: 67.3, highestScore: 96, lowestScore: 44, targetBenchmark: 72 },
    { testNumber: 'Test 6', testTitle: 'Rotational Mechanics & Equilibrium', classAverage: 69.8, highestScore: 95, lowestScore: 46, targetBenchmark: 75 },
    { testNumber: 'Test 7', testTitle: 'Full Syllabus Mock Test #7', classAverage: 74.2, highestScore: 98, lowestScore: 50, targetBenchmark: 75 },
  ],
  frequentlyMissedQuestions: [
    {
      questionNumber: 4,
      testTitle: 'Full Syllabus Mock Test #7',
      subject: 'Physics',
      topic: 'Rotational Dynamics',
      correctOption: 'D',
      missedPercentage: 68.4,
      commonWrongOption: 'B',
      rootCauseDiagnosis: '68% of students neglected the rolling friction couple when force acts at top of cylinder.',
    },
    {
      questionNumber: 11,
      testTitle: 'Full Syllabus Mock Test #7',
      subject: 'Chemistry',
      topic: 'Stoichiometry Limiting Reagent',
      correctOption: 'C',
      missedPercentage: 58.3,
      commonWrongOption: 'A',
      rootCauseDiagnosis: 'Molar mass normalization was missed prior to oxygen consumption calculation.',
    },
    {
      questionNumber: 19,
      testTitle: 'Full Syllabus Mock Test #7',
      subject: 'Mathematics',
      topic: 'Definite Integrals (Leibniz Rule)',
      correctOption: 'C',
      missedPercentage: 52.1,
      commonWrongOption: 'B',
      rootCauseDiagnosis: 'Chain rule derivative for the variable upper limit was omitted.',
    },
    {
      questionNumber: 27,
      testTitle: 'Full Syllabus Mock Test #7',
      subject: 'Physics',
      topic: 'Electrostatic Potential & Capacitance',
      correctOption: 'A',
      missedPercentage: 47.9,
      commonWrongOption: 'D',
      rootCauseDiagnosis: 'Dielectric insertion with battery connected vs disconnected formula confusion.',
    },
  ],
};

export const MOCK_TEST_PAPERS: TestPaper[] = [
  {
    id: 't-07',
    testNumber: 'Test 7',
    title: 'Full Syllabus Mock Test #7',
    batch: 'Batch A1 (JEE Advanced 2026)',
    subjectScope: 'Full Paper',
    dateConducted: '2026-08-14',
    totalMarks: 160,
    questionCount: 40,
    classAverage: 74.2,
    highestScore: 95.0,
    answerKey: {
      1: 'A', 2: 'C', 3: 'B', 4: 'D', 5: 'A', 6: 'B', 7: 'C', 8: 'A', 9: 'D', 10: 'B',
      11: 'C', 12: 'D', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'A', 18: 'B', 19: 'C', 20: 'D',
      21: 'A', 22: 'B', 23: 'C', 24: 'D', 25: 'A', 26: 'B', 27: 'A', 28: 'C', 29: 'B', 30: 'D',
      31: 'A', 32: 'C', 33: 'B', 34: 'D', 35: 'A', 36: 'B', 37: 'C', 38: 'D', 39: 'A', 40: 'B',
    },
  },
  {
    id: 't-06',
    testNumber: 'Test 6',
    title: 'Weekly Physics - Rotational Mechanics',
    batch: 'Batch A1 (JEE Advanced 2026)',
    subjectScope: 'Physics',
    dateConducted: '2026-08-08',
    totalMarks: 100,
    questionCount: 25,
    classAverage: 69.8,
    highestScore: 92.0,
    answerKey: {
      1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'A', 6: 'B', 7: 'C', 8: 'A', 9: 'D', 10: 'B',
      11: 'C', 12: 'D', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'A', 18: 'B', 19: 'C', 20: 'D',
      21: 'A', 22: 'B', 23: 'C', 24: 'D', 25: 'A',
    },
  },
  {
    id: 't-05',
    testNumber: 'Test 5',
    title: 'Organic Chemistry Reactions & Mechanisms',
    batch: 'Batch A1 (JEE Advanced 2026)',
    subjectScope: 'Chemistry',
    dateConducted: '2026-08-01',
    totalMarks: 100,
    questionCount: 25,
    classAverage: 67.3,
    highestScore: 96.0,
    answerKey: {
      1: 'C', 2: 'D', 3: 'A', 4: 'B', 5: 'C', 6: 'D', 7: 'A', 8: 'B', 9: 'C', 10: 'D',
      11: 'A', 12: 'B', 13: 'C', 14: 'D', 15: 'A', 16: 'B', 17: 'C', 18: 'D', 19: 'A', 20: 'B',
      21: 'C', 22: 'D', 23: 'A', 24: 'B', 25: 'C',
    },
  },
  {
    id: 't-04',
    testNumber: 'Test 4',
    title: 'Calculus & Coordinate Geometry Booster',
    batch: 'Batch A1 (JEE Advanced 2026)',
    subjectScope: 'Mathematics',
    dateConducted: '2026-07-22',
    totalMarks: 100,
    questionCount: 25,
    classAverage: 60.5,
    highestScore: 94.0,
    answerKey: {
      1: 'B', 2: 'C', 3: 'D', 4: 'A', 5: 'B', 6: 'C', 7: 'D', 8: 'A', 9: 'B', 10: 'C',
      11: 'D', 12: 'A', 13: 'B', 14: 'C', 15: 'D', 16: 'A', 17: 'B', 18: 'C', 19: 'D', 20: 'A',
      21: 'B', 22: 'C', 23: 'D', 24: 'A', 25: 'B',
    },
  },
];

export const MOCK_ASSIGNMENTS: MockAssignment[] = [
  {
    id: 'asg-01',
    title: 'Rotational Dynamics Remediation Quiz',
    description: 'Targeted practice for rolling friction and moment of inertia centroids.',
    subject: 'Physics',
    targetTopic: 'Rotational Kinematics',
    difficulty: 'Medium',
    questionCount: 5,
    assignedBy: 'Dr. Vikram Malhotra',
    assignedToBatch: 'Batch A1 (JEE Advanced 2026)',
    dueDate: '2026-08-18',
    status: 'assigned',
    xpReward: 150,
  },
  {
    id: 'asg-02',
    title: 'Stoichiometry & Limiting Reagents Sprint',
    description: 'Master molar ratios, combustion reactions, and theoretical yield calculation.',
    subject: 'Chemistry',
    targetTopic: 'Stoichiometry Limiting Reagents',
    difficulty: 'Easy',
    questionCount: 5,
    assignedBy: 'AI Adaptive Engine',
    assignedToBatch: 'Batch A1 (JEE Advanced 2026)',
    assignedToStudentId: 's-01',
    dueDate: '2026-08-17',
    status: 'in_progress',
    xpReward: 100,
  },
  {
    id: 'asg-03',
    title: 'Definite Integration & Leibniz Drill',
    description: 'High-yield calculus problems involving differentiation under integral sign.',
    subject: 'Mathematics',
    targetTopic: 'Definite Integrals',
    difficulty: 'Hard',
    questionCount: 8,
    assignedBy: 'AI Adaptive Engine',
    assignedToBatch: 'Batch A1 (JEE Advanced 2026)',
    dueDate: '2026-08-20',
    status: 'assigned',
    xpReward: 200,
  },
  {
    id: 'asg-04',
    title: 'Electrostatics & Field Lines Quick Check',
    description: 'Conceptual check on Gauss law and dielectric slabs.',
    subject: 'Physics',
    targetTopic: 'Electrostatic Potential',
    difficulty: 'Medium',
    questionCount: 6,
    assignedBy: 'Dr. Vikram Malhotra',
    assignedToBatch: 'Batch A1 (JEE Advanced 2026)',
    dueDate: '2026-08-16',
    status: 'completed',
    score: 90,
    xpReward: 120,
  },
];

export const MOCK_WEAK_TOPICS: WeakTopicItem[] = [
  {
    id: 'topic-rotational-kinematics',
    subject: 'Physics',
    name: 'Rotational Kinematics & Pure Rolling',
    status: 'studying',
    mistakesCount: 3,
    lastTestedDate: '2026-08-14',
    conceptExplanation: 'Pure rolling requires zero relative velocity at the contact point. When a pulling force is applied at distance r from COM, friction force direction depends on whether I_cm < M*R*r.',
    formula: 'a_cm = (F + f) / M  and  α = (F*r - f*R) / I_cm',
    exampleProblem: {
      question: 'A solid disk (I = 1/2 M R^2) is pulled with force F at the central axle. What is the acceleration of the center of mass without slipping?',
      steps: [
        'Apply Newton 2nd Law for translation: F - f = M * a',
        'Apply torque about COM: f * R = (1/2 M R^2) * (a / R) -> f = 1/2 M * a',
        'Substitute f into linear equation: F - 1/2 M * a = M * a -> F = 3/2 M * a',
        'Solve for a: a = 2F / (3M)',
      ],
      solution: 'a = (2/3) * (F / M)',
    },
  },
  {
    id: 'topic-stoichiometry',
    subject: 'Chemistry',
    name: 'Stoichiometry & Limiting Reagents',
    status: 'ready',
    mistakesCount: 2,
    lastTestedDate: '2026-08-14',
    conceptExplanation: 'The limiting reagent is determined by dividing given moles by the stoichiometric coefficient. The reactant with the smallest ratio is exhausted first.',
    formula: 'Moles = Mass / MolarMass ; Ratio = Moles / Coefficient',
    exampleProblem: {
      question: 'If 4 moles of H2 react with 3 moles of O2 to form H2O, which reactant is limiting?',
      steps: [
        'Balanced Reaction: 2 H2 + O2 -> 2 H2O',
        'Ratio for H2: 4 / 2 = 2.0',
        'Ratio for O2: 3 / 1 = 3.0',
        'H2 has the lower ratio (2.0 < 3.0), therefore H2 is the limiting reactant.',
      ],
      solution: 'Hydrogen (H2) is limiting.',
    },
  },
  {
    id: 'topic-definite-integrals',
    subject: 'Mathematics',
    name: 'Leibniz Rule & Definite Integrals',
    status: 'not_started',
    mistakesCount: 2,
    lastTestedDate: '2026-08-14',
    conceptExplanation: 'When differentiating an integral with variable limits, apply Leibniz rule: d/dx ∫[u(x) to v(x)] f(t) dt = f(v(x)) * v\'(x) - f(u(x)) * u\'(x).',
    formula: 'd/dx ∫[u(x) to v(x)] f(t) dt = f(v(x))·v\'(x) - f(u(x))·u\'(x)',
    exampleProblem: {
      question: 'Find d/dx ∫[0 to x^2] sin(t) dt.',
      steps: [
        'Identify upper limit v(x) = x^2, with v\'(x) = 2x.',
        'Identify lower limit u(x) = 0, with u\'(x) = 0.',
        'Evaluate integrand at upper limit: f(v(x)) = sin(x^2).',
        'Apply Leibniz: sin(x^2) * (2x) - sin(0) * 0 = 2x sin(x^2).',
      ],
      solution: '2x · sin(x^2)',
    },
  },
  {
    id: 'topic-electrostatics',
    subject: 'Physics',
    name: 'Electrostatic Potential & Dielectrics',
    status: 'not_started',
    mistakesCount: 1,
    lastTestedDate: '2026-08-01',
    conceptExplanation: 'When dielectric K is inserted with battery disconnected, Charge Q remains constant, Capacitance C increases by K, and Voltage V decreases by V/K.',
    formula: 'C\' = K * C_0 ; V\' = V_0 / K ; U\' = U_0 / K (Battery disconnected)',
  },
  {
    id: 'topic-coordination',
    subject: 'Chemistry',
    name: 'Coordination Compounds & Crystal Field',
    status: 'mastered',
    mistakesCount: 0,
    lastTestedDate: '2026-07-28',
    conceptExplanation: 'Crystal field splitting parameter Δ_o determines strong field (low spin, pairing) vs weak field (high spin, Hund\'s rule).',
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, studentId: 's-02', name: 'Aarav Mehta', avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop', batch: 'Batch A1', score: 980, totalXp: 2450, streak: 28, accuracy: 96, tier: 'Platinum' },
  { rank: 2, studentId: 's-03', name: 'Ananya Iyer', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop', batch: 'Batch A1', score: 945, totalXp: 2120, streak: 21, accuracy: 92, tier: 'Platinum' },
  { rank: 3, studentId: 's-04', name: 'Devansh Patel', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop', batch: 'Batch A1', score: 920, totalXp: 1890, streak: 18, accuracy: 88, tier: 'Gold' },
  { rank: 4, studentId: 's-01', name: 'Rohan Sharma (You)', avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=200&auto=format&fit=crop', batch: 'Batch A1', score: 890, totalXp: 1240, streak: 15, accuracy: 82, isCurrentStudent: true, tier: 'Gold' },
  { rank: 5, studentId: 's-05', name: 'Ishita Gupta', avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop', batch: 'Batch A1', score: 850, totalXp: 1100, streak: 11, accuracy: 79, tier: 'Gold' },
  { rank: 6, studentId: 's-06', name: 'Kabir Verma', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop', batch: 'Batch A1', score: 810, totalXp: 950, streak: 9, accuracy: 74, tier: 'Silver' },
  { rank: 7, studentId: 's-07', name: 'Priya Nair', avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop', batch: 'Batch A1', score: 760, totalXp: 820, streak: 6, accuracy: 70, tier: 'Silver' },
  { rank: 8, studentId: 's-08', name: 'Siddharth Joshi', avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=200&auto=format&fit=crop', batch: 'Batch A1', score: 710, totalXp: 680, streak: 4, accuracy: 63, tier: 'Bronze' },
];

export const MOCK_LATEST_DIAGNOSTIC: TestDiagnosticResult = {
  testId: 't-07',
  testTitle: 'Full Syllabus Mock Test #7',
  section: 'Full Paper',
  submissionDate: '2026-08-14T20:30:00Z',
  studentScore: 120,
  totalMarks: 160,
  percentage: 75.0,
  accuracy: 82.5,
  rank: 4,
  physicsScore: 42,
  chemistryScore: 46,
  mathsScore: 32,
  feedbackSummary: "Great performance! You scored 120/160 (75%), gaining +8% from your prior mock. Strong in Organic Chemistry, while Rotational Kinematics & Leibniz rule need targeted review.",
  weakGaps: [
    {
      id: 'gap-01',
      topic: 'Rotational Kinematics',
      subject: 'Physics',
      mistakesCount: 3,
      insight: "You consistently applied linear equations instead of angular ones. Remember to map 'v' to 'ω' and 'a' to 'α'.",
      recommendedRemediation: 'Watch 5m Concept Recap & practice 5 targeted MCQs.',
      practiceTopicId: 'topic-rotational-kinematics',
    },
    {
      id: 'gap-02',
      topic: 'Stoichiometry Limiting Reagents',
      subject: 'Chemistry',
      mistakesCount: 2,
      insight: "Calculation errors spotted. You identified the reaction, but didn't normalize by molar mass first.",
      recommendedRemediation: 'Review molar mass ratios and complete 5-question sprint.',
      practiceTopicId: 'topic-stoichiometry',
    },
  ],
  questionBreakdown: [
    { questionNumber: 1, subject: 'Physics', topic: 'Kinematics', studentOption: 'A', correctOption: 'A', isCorrect: true, status: 'correct', confidence: 0.98, aiNote: 'Perfect application of Newton second law.' },
    { questionNumber: 2, subject: 'Physics', topic: 'Work & Energy', studentOption: 'C', correctOption: 'C', isCorrect: true, status: 'correct', confidence: 0.95, aiNote: 'Clean conservation of mechanical energy.' },
    { questionNumber: 3, subject: 'Physics', topic: 'Circular Motion', studentOption: 'unattempted', correctOption: 'B', isCorrect: false, status: 'skipped', confidence: 0.99, aiNote: 'Smart strategic skip for time management.' },
    { questionNumber: 4, subject: 'Physics', topic: 'Rotational Dynamics', studentOption: 'B', correctOption: 'D', isCorrect: false, status: 'incorrect', confidence: 0.94, aiNote: 'Marked (B), correct was (D). Neglected contact rolling friction.' },
    { questionNumber: 11, subject: 'Chemistry', topic: 'Limiting Reagent', studentOption: 'A', correctOption: 'C', isCorrect: false, status: 'incorrect', confidence: 0.96, aiNote: 'Marked (A), correct was (C). Molar mass normalization missed.' },
    { questionNumber: 12, subject: 'Chemistry', topic: 'Atomic Structure', studentOption: 'D', correctOption: 'D', isCorrect: true, status: 'correct', confidence: 0.99, aiNote: 'Flawless calculation of de Broglie wavelength.' },
    { questionNumber: 19, subject: 'Mathematics', topic: 'Definite Integrals', studentOption: 'B', correctOption: 'C', isCorrect: false, status: 'incorrect', confidence: 0.92, aiNote: 'Marked (B), correct was (C). Omitted Leibniz chain factor 2x.' },
  ],
};
